LABOUR_CATEGORY_LIST = {
    "Mason": "Mason",
    "Carpenter": "Carpenter",
    "Bar_Bender": "Bar Bender",
    "Electrician": "Electrician",
    "Plumber": "Plumber",
    "Painter": "Painter",
    "Scaffolder": "Scaffolder",
    "Foreman": "Foreman",
    "Surveyor": "Surveyor",
    "Crane_Operator": "Crane Operator",
    "Excavator_Operator": "Excavator Operator",
    "Rigger": "Rigger",
    "Heavy_Equipment_Operator": "Heavy Equipment Operator",
    "JCB_Operator": "JCB Operator",
    "Concrete_Pump_Operator": "Concrete Pump Operator",
    "Welder": "Welder",
    "Fitter": "Fitter",
    "Gas_Cutter": "Gas Cutter",
    "Helper": "Helper",
    "Unskill": "Unskill",
}
