"""add sale order and certified bill

Revision ID: 07872936378d
Revises: 82d83ca2c686
Create Date: 2026-07-31 15:49:05.607145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07872936378d'
down_revision = '82d83ca2c686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certified_bill_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certified_bill_no', sa.String(length=50), nullable=False),
    sa.Column('certified_bill_uuid', sa.String(length=36), nullable=True),
    sa.Column('certified_bill_date', sa.Date(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('job_location', sa.String(length=200), nullable=True),
    sa.Column('pre_certified_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('this_bill_claim', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_claim', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('attachment', sa.Text(), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certified_bill_no')
    )
    with op.batch_alter_table('certified_bill_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certified_bill_master_certified_bill_uuid'), ['certified_bill_uuid'], unique=True)

    op.create_table('sale_order_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_order_no', sa.String(length=50), nullable=False),
    sa.Column('sale_order_uuid', sa.String(length=36), nullable=True),
    sa.Column('sale_order_date', sa.Date(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('job_location', sa.String(length=200), nullable=True),
    sa.Column('pre_certified_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('this_bill_claim', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_claim', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('attachment', sa.Text(), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_order_no')
    )
    with op.batch_alter_table('sale_order_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_order_master_sale_order_uuid'), ['sale_order_uuid'], unique=True)

    op.create_table('certified_bill_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certified_bill_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=True),
    sa.Column('item_name_desc', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('claim_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certified_bill_id'], ['certified_bill_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_order_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=True),
    sa.Column('item_name_desc', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('claim_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_order_id'], ['sale_order_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_order_items')
    op.drop_table('certified_bill_items')
    with op.batch_alter_table('sale_order_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_order_master_sale_order_uuid'))

    op.drop_table('sale_order_master')
    with op.batch_alter_table('certified_bill_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certified_bill_master_certified_bill_uuid'))

    op.drop_table('certified_bill_master')
    # ### end Alembic commands ###
