"""add journal entry tables

Revision ID: 07f3183282f6
Revises: 08cf76b7a7aa
Create Date: 2026-09-01 18:16:12.443231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f3183282f6'
down_revision = '08cf76b7a7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entry_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_no', sa.String(length=50), nullable=False),
    sa.Column('journal_uuid', sa.String(length=36), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_credit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entry_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_master_journal_uuid'), ['journal_uuid'], unique=True)

    op.create_table('journal_entry_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('dr_cr', sa.String(length=3), nullable=False),
    sa.Column('cc_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cc_id'], ['cc_codes.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entry_master.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_entry_lines')
    with op.batch_alter_table('journal_entry_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entry_master_journal_uuid'))

    op.drop_table('journal_entry_master')
    # ### end Alembic commands ###
