"""item some bug fixed

Revision ID: 08953e7e5677
Revises: 88ed6184b763
Create Date: 2026-07-04 12:41:30.127400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08953e7e5677'
down_revision = '88ed6184b763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indent_items', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=1500),
               existing_nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('item_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=2000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('item_name',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('indent_items', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###
