"""add ledger

Revision ID: 08cf76b7a7aa
Revises: 0b9de5321e07
Create Date: 2026-08-14 08:56:29.835537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cf76b7a7aa'
down_revision = '0b9de5321e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_note_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vendors', ['vendor_id'], ['id'])

    with op.batch_alter_table('debit_note_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vendors', ['vendor_id'], ['id'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_vendors_vendor_uuid'), ['vendor_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_vendor_uuid'))
        batch_op.drop_column('vendor_uuid')

    with op.batch_alter_table('debit_note_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vendor_id')

    with op.batch_alter_table('credit_note_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###
