"""add payment

Revision ID: 0b9de5321e07
Revises: 566d5335a595
Create Date: 2026-08-11 18:06:45.639042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9de5321e07'
down_revision = '566d5335a595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_voucher_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_vouch_no', sa.String(length=50), nullable=False),
    sa.Column('payment_vouch_uuid', sa.String(length=36), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('purchase_voucher_id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('payment_mode', sa.String(length=10), nullable=True),
    sa.Column('cash_ac_id', sa.Integer(), nullable=True),
    sa.Column('bank_ac_id', sa.Integer(), nullable=True),
    sa.Column('utr_voucher_no', sa.String(length=200), nullable=True),
    sa.Column('payment_remarks', sa.Text(), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('round_off', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_invoice_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bank_ac_id'], ['bank_cash.id'], ),
    sa.ForeignKeyConstraint(['cash_ac_id'], ['bank_cash.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['purchase_voucher_id'], ['purchase_voucher_master.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_voucher_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_voucher_master_payment_vouch_uuid'), ['payment_vouch_uuid'], unique=True)

    op.create_table('payment_voucher_gst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_voucher_id', sa.Integer(), nullable=False),
    sa.Column('gst_type', sa.String(length=10), nullable=False),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=200), nullable=True),
    sa.Column('booked_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_voucher_id'], ['payment_voucher_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_voucher_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_voucher_id', sa.Integer(), nullable=False),
    sa.Column('pv_item_id', sa.Integer(), nullable=True),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('cc_code_id', sa.Integer(), nullable=True),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=200), nullable=True),
    sa.Column('booked_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cc_code_id'], ['cc_codes.id'], ),
    sa.ForeignKeyConstraint(['payment_voucher_id'], ['payment_voucher_master.id'], ),
    sa.ForeignKeyConstraint(['pv_item_id'], ['purchase_voucher_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_payment_receipt_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.String(length=50), nullable=False),
    sa.Column('receipt_uuid', sa.String(length=36), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('purchase_bill_id', sa.Integer(), nullable=False),
    sa.Column('bvs_date', sa.Date(), nullable=True),
    sa.Column('vendor_bill_no', sa.String(length=100), nullable=True),
    sa.Column('vendor_bill_date', sa.Date(), nullable=True),
    sa.Column('order_no', sa.String(length=100), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('payment_mode', sa.String(length=10), nullable=True),
    sa.Column('cash_ac_id', sa.Integer(), nullable=True),
    sa.Column('bank_ac_id', sa.Integer(), nullable=True),
    sa.Column('utr_voucher_no', sa.String(length=200), nullable=True),
    sa.Column('payment_remarks', sa.Text(), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('round_off', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_invoice_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bank_ac_id'], ['bank_cash.id'], ),
    sa.ForeignKeyConstraint(['cash_ac_id'], ['bank_cash.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['purchase_bill_id'], ['purchase_bill_master.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_payment_receipt_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_payment_receipt_master_receipt_uuid'), ['receipt_uuid'], unique=True)

    op.create_table('bill_payment_receipt_gst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('gst_type', sa.String(length=10), nullable=False),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=200), nullable=True),
    sa.Column('booked_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['bill_payment_receipt_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_payment_receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('pb_item_id', sa.Integer(), nullable=True),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=200), nullable=True),
    sa.Column('booked_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pb_item_id'], ['purchase_bill_items.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['bill_payment_receipt_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_payment_receipt_items')
    op.drop_table('bill_payment_receipt_gst')
    with op.batch_alter_table('bill_payment_receipt_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_payment_receipt_master_receipt_uuid'))

    op.drop_table('bill_payment_receipt_master')
    op.drop_table('payment_voucher_items')
    op.drop_table('payment_voucher_gst')
    with op.batch_alter_table('payment_voucher_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_voucher_master_payment_vouch_uuid'))

    op.drop_table('payment_voucher_master')
    # ### end Alembic commands ###
