""" brr fixed

Revision ID: 0f89bfca854d
Revises: 407167849387
Create Date: 2026-07-21 01:19:21.021146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f89bfca854d'
down_revision = '407167849387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brr_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booked_amount', sa.Numeric(precision=18, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brr_master', schema=None) as batch_op:
        batch_op.drop_column('booked_amount')

    # ### end Alembic commands ###
