"""add sale order 

Revision ID: 1604a9b842ee
Revises: 07872936378d
Create Date: 2026-08-01 10:34:41.713943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1604a9b842ee'
down_revision = '07872936378d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('og_sale_order_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('og_sale_order_no', sa.String(length=50), nullable=False),
    sa.Column('og_sale_order_uuid', sa.String(length=36), nullable=True),
    sa.Column('og_sale_order_date', sa.Date(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=True),
    sa.Column('order_validity', sa.Date(), nullable=True),
    sa.Column('order_title', sa.String(length=200), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('attachment_1', sa.Text(), nullable=True),
    sa.Column('attachment_2', sa.Text(), nullable=True),
    sa.Column('attachment_3', sa.Text(), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('og_sale_order_no')
    )
    with op.batch_alter_table('og_sale_order_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_og_sale_order_master_og_sale_order_uuid'), ['og_sale_order_uuid'], unique=True)

    op.create_table('og_sale_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('og_sale_order_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=True),
    sa.Column('item_name_desc', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('order_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['og_sale_order_id'], ['og_sale_order_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('og_sale_order_items')
    with op.batch_alter_table('og_sale_order_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_og_sale_order_master_og_sale_order_uuid'))

    op.drop_table('og_sale_order_master')
    # ### end Alembic commands ###
