"""term

Revision ID: 17f01df781b0
Revises: 9c70e479fafd
Create Date: 2026-07-18 12:24:41.059218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f01df781b0'
down_revision = '9c70e479fafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('sub_module', sa.String(), nullable=False),
    sa.Column('term_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('term_id')
    )
    op.create_table('term_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('point_style', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('term_points',
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['term_groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('point_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term_points')
    op.drop_table('term_groups')
    op.drop_table('terms')
    # ### end Alembic commands ###
