"""bankcash

Revision ID: 1bcc564b404f
Revises: 4c9a86fca0d9
Create Date: 2026-09-06 16:40:15.913773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bcc564b404f'
down_revision = '4c9a86fca0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_cash_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_cash_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_cash_id'], ['bank_cash.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_cash_id', 'project_id', name='uq_bank_cash_project')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_cash_project')
    # ### end Alembic commands ###
