"""Store location

Revision ID: 20e51d7f8606
Revises: 708a842532ab
Create Date: 2026-07-12 16:21:04.367625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e51d7f8606'
down_revision = '708a842532ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Projectlocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('location_type', sa.String(), nullable=True),
    sa.Column('project_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code', 'location_name', 'location_type', name='uq_project_location_name_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Projectlocation')
    # ### end Alembic commands ###
