"""dlr

Revision ID: 281c1dbe36ef
Revises: 6360db165aa1
Create Date: 2026-07-26 12:42:15.760729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281c1dbe36ef'
down_revision = '6360db165aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dlr_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dlr_no', sa.String(length=50), nullable=False),
    sa.Column('dlr_date', sa.Date(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('report_by', sa.String(length=200), nullable=True),
    sa.Column('verified_by', sa.String(length=200), nullable=True),
    sa.Column('scan_copy', sa.String(length=500), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dlr_no')
    )
    op.create_table('dlr_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dlr_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('man_id', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('finish_time', sa.String(length=10), nullable=True),
    sa.Column('lunch_hour', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('working_hour', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bonus_hour', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_working_hr', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('job_location', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dlr_id'], ['dlr_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dlr_items')
    op.drop_table('dlr_master')
    # ### end Alembic commands ###
