"""purchase voucher item use cc_code_id fk

Revision ID: 28ccf41b2523
Revises: 327a1dbdb31e
Create Date: 2026-08-03 23:57:57.955905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ccf41b2523'
down_revision = '327a1dbdb31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_receipt_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.String(length=50), nullable=False),
    sa.Column('receipt_uuid', sa.String(length=36), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('og_sale_order_no', sa.String(length=50), nullable=True),
    sa.Column('og_sale_order_id', sa.Integer(), nullable=True),
    sa.Column('sale_order_date', sa.Date(), nullable=True),
    sa.Column('certified_bill_id', sa.Integer(), nullable=True),
    sa.Column('certified_bill_no', sa.String(length=50), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('invoice_no', sa.String(length=200), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('bill_to_address', sa.Text(), nullable=True),
    sa.Column('ship_to_address', sa.Text(), nullable=True),
    sa.Column('bill_abstract_no', sa.String(length=200), nullable=True),
    sa.Column('bill_abstract_date', sa.Date(), nullable=True),
    sa.Column('payment_mode', sa.String(length=10), nullable=True),
    sa.Column('cash_ac_id', sa.Integer(), nullable=True),
    sa.Column('bank_ac_id', sa.Integer(), nullable=True),
    sa.Column('utr_voucher_no', sa.String(length=200), nullable=True),
    sa.Column('payment_remarks', sa.Text(), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('round_off', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_invoice_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bank_ac_id'], ['bank_cash.id'], ),
    sa.ForeignKeyConstraint(['cash_ac_id'], ['bank_cash.id'], ),
    sa.ForeignKeyConstraint(['certified_bill_id'], ['billing_master.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['og_sale_order_id'], ['og_sale_order_master.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_receipt_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_receipt_master_receipt_uuid'), ['receipt_uuid'], unique=True)

    op.create_table('sale_receipt_gst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('gst_type', sa.String(length=10), nullable=False),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=200), nullable=True),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('booked_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('received_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('balance_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['sale_receipt_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=200), nullable=True),
    sa.Column('booked_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('received_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('balance_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['sale_receipt_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_receipt_items')
    op.drop_table('sale_receipt_gst')
    with op.batch_alter_table('sale_receipt_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_receipt_master_receipt_uuid'))

    op.drop_table('sale_receipt_master')
    # ### end Alembic commands ###
