"""fix

Revision ID: 34ae9d371baa
Revises: 3c2f9e26ee41
Create Date: 2026-08-08 16:37:46.093562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ae9d371baa'
down_revision = '3c2f9e26ee41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batching_plant_master', schema=None) as batch_op:
        batch_op.alter_column('volume_of_concrete',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('weight_of_concrete',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('pm_master', schema=None) as batch_op:
        batch_op.alter_column('purchased_bill_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('pm_service_history', schema=None) as batch_op:
        batch_op.alter_column('bill_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('pm_service_schedule', schema=None) as batch_op:
        batch_op.alter_column('expected_expenses',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pm_service_schedule', schema=None) as batch_op:
        batch_op.alter_column('expected_expenses',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('pm_service_history', schema=None) as batch_op:
        batch_op.alter_column('bill_amount',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('pm_master', schema=None) as batch_op:
        batch_op.alter_column('purchased_bill_amount',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('batching_plant_master', schema=None) as batch_op:
        batch_op.alter_column('weight_of_concrete',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('volume_of_concrete',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
