"""fix

Revision ID: 3c2f9e26ee41
Revises: 
Create Date: 2026-08-08 16:07:02.282694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2f9e26ee41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_boq_items', schema=None) as batch_op:
        batch_op.alter_column('claim_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('billing_items', schema=None) as batch_op:
        batch_op.alter_column('claim_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('brb_items', schema=None) as batch_op:
        batch_op.alter_column('billing_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('bss_items', schema=None) as batch_op:
        batch_op.alter_column('billing_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('bvs_items', schema=None) as batch_op:
        batch_op.alter_column('billing_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('dc_items', schema=None) as batch_op:
        batch_op.alter_column('issue_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('gin_items', schema=None) as batch_op:
        batch_op.alter_column('issue_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('grn_items', schema=None) as batch_op:
        batch_op.alter_column('order_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('pre_received_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('balance_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('current_received_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('indent_items', schema=None) as batch_op:
        batch_op.alter_column('qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('og_sale_order_boq_items', schema=None) as batch_op:
        batch_op.alter_column('order_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('og_sale_order_items', schema=None) as batch_op:
        batch_op.alter_column('order_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('amend_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('used_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('balance_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('pw_order_items', schema=None) as batch_op:
        batch_op.alter_column('qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('amend_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('used_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('balance_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('srn_items', schema=None) as batch_op:
        batch_op.alter_column('current_received_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=17, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('srn_items', schema=None) as batch_op:
        batch_op.alter_column('current_received_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('pw_order_items', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('balance_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('used_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('amend_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('balance_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('used_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('amend_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('og_sale_order_items', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('order_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('og_sale_order_boq_items', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('order_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('indent_items', schema=None) as batch_op:
        batch_op.alter_column('qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('grn_items', schema=None) as batch_op:
        batch_op.alter_column('current_received_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('balance_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('pre_received_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('order_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('gin_items', schema=None) as batch_op:
        batch_op.alter_column('issue_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('dc_items', schema=None) as batch_op:
        batch_op.alter_column('issue_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('bvs_items', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('billing_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('bss_items', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('billing_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('brb_items', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('billing_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('billing_items', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('claim_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('billing_boq_items', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('claim_qty',
               existing_type=sa.Numeric(precision=17, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
