"""Gross fix

Revision ID: 3c99cab2349d
Revises: 
Create Date: 2026-07-18 18:11:16.342864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c99cab2349d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_terms_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_term_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'terms', ['source_term_id'], ['term_id'])

    with op.batch_alter_table('pw_order_terms_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_term_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'terms', ['source_term_id'], ['term_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pw_order_terms_conditions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_term_id')

    with op.batch_alter_table('order_terms_conditions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_term_id')

    # ### end Alembic commands ###
