""" pdf left and new billing fixed

Revision ID: 3ce6ab5f6910
Revises: ab20c12b9215
Create Date: 2026-07-23 15:30:14.239216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce6ab5f6910'
down_revision = 'ab20c12b9215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brr_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brr_no', sa.String(length=50), nullable=False),
    sa.Column('brr_date', sa.Date(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('order_category', sa.String(length=100), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('pw_order_id', sa.Integer(), nullable=True),
    sa.Column('party_bill_no', sa.String(length=100), nullable=True),
    sa.Column('party_date', sa.Date(), nullable=True),
    sa.Column('booked_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('received_category', sa.String(length=200), nullable=True),
    sa.Column('submitted_by_name', sa.String(length=200), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('received_through', sa.String(length=200), nullable=True),
    sa.Column('received_reference', sa.String(length=200), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('attached_doc', sa.String(length=500), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order_master.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['pw_order_id'], ['pw_order_master.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brr_no')
    )
    with op.batch_alter_table('brb_master', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'brr_master', ['brr_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brb_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('brr_master')
    # ### end Alembic commands ###
