""" pdf uuid

Revision ID: 407167849387
Revises: 533d7e873e80
Create Date: 2026-07-20 13:42:50.962754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407167849387'
down_revision = '533d7e873e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indent_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indent_uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_indent_master_indent_uuid'), ['indent_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indent_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indent_master_indent_uuid'))
        batch_op.drop_column('indent_uuid')

    # ### end Alembic commands ###
