"""docket vouchar

Revision ID: 44cf3455299a
Revises: b5bab715a1ec
Create Date: 2026-09-04 20:57:40.684224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44cf3455299a'
down_revision = 'b5bab715a1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petty_cash_docket_voucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_uuid', sa.String(length=36), nullable=True),
    sa.Column('voucher_no', sa.String(length=30), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('expenses_by', sa.String(length=100), nullable=False),
    sa.Column('mode_of_payment', sa.String(length=30), nullable=False),
    sa.Column('fund_source', sa.String(length=50), nullable=False),
    sa.Column('payment_ref_id', sa.String(length=100), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['budget_id'], ['petty_cash_budget.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('petty_cash_docket_voucher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_petty_cash_docket_voucher_voucher_uuid'), ['voucher_uuid'], unique=True)

    op.create_table('petty_cash_docket_voucher_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('cc_code', sa.String(length=20), nullable=True),
    sa.Column('cc_name', sa.String(length=100), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['voucher_id'], ['petty_cash_docket_voucher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petty_cash_docket_voucher_detail')
    with op.batch_alter_table('petty_cash_docket_voucher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_petty_cash_docket_voucher_voucher_uuid'))

    op.drop_table('petty_cash_docket_voucher')
    # ### end Alembic commands ###
