"""contact person 

Revision ID: 45dbfed2db31
Revises: e1b6adf9186d
Create Date: 2026-06-24 14:02:07.489082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45dbfed2db31'
down_revision = 'e1b6adf9186d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_person', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=50), nullable=True))

    with op.batch_alter_table('pw_order_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_person', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pw_order_master', schema=None) as batch_op:
        batch_op.drop_column('contact_number')
        batch_op.drop_column('contact_person')

    with op.batch_alter_table('order_master', schema=None) as batch_op:
        batch_op.drop_column('contact_number')
        batch_op.drop_column('contact_person')

    # ### end Alembic commands ###
