"""Journalaccounting

Revision ID: 4c9a86fca0d9
Revises: 136f076ba8b1
Create Date: 2026-09-06 13:29:00.102888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9a86fca0d9'
down_revision = '136f076ba8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petty_cash_journal_accounting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_no', sa.String(length=50), nullable=False),
    sa.Column('voucher_uuid', sa.String(length=36), nullable=True),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('journal_voucher_id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_voucher_id'], ['petty_cash_journal_voucher.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_voucher_id')
    )
    with op.batch_alter_table('petty_cash_journal_accounting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_petty_cash_journal_accounting_voucher_uuid'), ['voucher_uuid'], unique=True)

    op.create_table('petty_cash_journal_accounting_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_accounting_id', sa.Integer(), nullable=False),
    sa.Column('journal_line_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=100), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['journal_accounting_id'], ['petty_cash_journal_accounting.id'], ),
    sa.ForeignKeyConstraint(['journal_line_id'], ['petty_cash_journal_line.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_line_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petty_cash_journal_accounting_line')
    with op.batch_alter_table('petty_cash_journal_accounting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_petty_cash_journal_accounting_voucher_uuid'))

    op.drop_table('petty_cash_journal_accounting')
    # ### end Alembic commands ###
