"""sale_order_billing schema

Revision ID: 53231f5d3f89
Revises: 1604a9b842ee
Create Date: 2026-08-01 22:33:29.678274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53231f5d3f89'
down_revision = '1604a9b842ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('og_sale_order_items', schema=None) as batch_op:
        batch_op.alter_column('item_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(None, 'items', ['item_code'], ['item_code'])

    with op.batch_alter_table('sale_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('og_sale_order_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'og_sale_order_items', ['og_sale_order_item_id'], ['id'])

    with op.batch_alter_table('sale_order_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('og_sale_order_no', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('og_sale_order_id', sa.Integer(), nullable=True))
        batch_op.drop_column('order_type')
        batch_op.drop_column('order_id')
        batch_op.drop_column('order_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_order_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('order_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('og_sale_order_id')
        batch_op.drop_column('og_sale_order_no')

    with op.batch_alter_table('sale_order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('og_sale_order_item_id')

    with op.batch_alter_table('og_sale_order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('item_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
