"""vendor

Revision ID: 561caaded4f0
Revises: 20e51d7f8606
Create Date: 2026-07-16 00:26:14.601189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561caaded4f0'
down_revision = '20e51d7f8606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('corporate_address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('supplier_types', sa.JSON(), nullable=True),
    sa.Column('nature_of_service', sa.String(length=200), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code')
    )
    op.create_table('supplier_ledger_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'ledger_id', name='uq_supplier_ledger')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('supplier_types', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('nature_of_service', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('service_description', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_description')
        batch_op.drop_column('nature_of_service')
        batch_op.drop_column('supplier_types')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('email')

    op.drop_table('supplier_ledger_map')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
