"""add credit note tables

Revision ID: 566d5335a595
Revises: 86b3e73de4a9
Create Date: 2026-08-09 18:18:53.950441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566d5335a595'
down_revision = '86b3e73de4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_note_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_note_no', sa.String(length=50), nullable=False),
    sa.Column('credit_note_uuid', sa.String(length=36), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('bill_number', sa.String(length=200), nullable=True),
    sa.Column('bill_date', sa.Date(), nullable=True),
    sa.Column('order_number', sa.String(length=200), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('vendor_name', sa.String(length=300), nullable=True),
    sa.Column('vendor_gstn', sa.String(length=50), nullable=True),
    sa.Column('debit_note_no', sa.String(length=200), nullable=True),
    sa.Column('debit_note_date', sa.Date(), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_note_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_note_master_credit_note_uuid'), ['credit_note_uuid'], unique=True)

    op.create_table('credit_note_gst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_note_id', sa.Integer(), nullable=False),
    sa.Column('gst_type', sa.String(length=10), nullable=False),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=200), nullable=True),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_note_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_note_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_note_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_note_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_note_items')
    op.drop_table('credit_note_gst')
    with op.batch_alter_table('credit_note_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_note_master_credit_note_uuid'))

    op.drop_table('credit_note_master')
    # ### end Alembic commands ###
