"""accounts sale bill bank acc

Revision ID: 617f3f157960
Revises: f14ba9af90f4
Create Date: 2026-08-03 17:38:52.222746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617f3f157960'
down_revision = 'f14ba9af90f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_bill_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_ac_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bank_cash', ['bank_ac_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_bill_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bank_ac_id')

    # ### end Alembic commands ###
