"""add budget_detail_id to docket voucher detail

Revision ID: 635f9a11f8f9
Revises: 44cf3455299a
Create Date: 2026-09-05 11:46:26.283379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635f9a11f8f9'
down_revision = '44cf3455299a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petty_cash_docket_voucher_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_detail_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'petty_cash_budget_detail', ['budget_detail_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petty_cash_docket_voucher_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('budget_detail_id')

    # ### end Alembic commands ###
