"""add manpower_workers table

Revision ID: 6360db165aa1
Revises: 3ce6ab5f6910
Create Date: 2026-07-26 11:43:44.558199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6360db165aa1'
down_revision = '3ce6ab5f6910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manpower_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('man_id', sa.String(length=20), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('father_name', sa.String(length=200), nullable=True),
    sa.Column('nominee', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('rate_per_manday', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('aadhar_number', sa.String(length=20), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('uan', sa.String(length=30), nullable=True),
    sa.Column('esic', sa.String(length=30), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('branch_name', sa.String(length=150), nullable=True),
    sa.Column('ifsc_code', sa.String(length=50), nullable=True),
    sa.Column('aadhar_file', sa.String(length=300), nullable=True),
    sa.Column('pan_file', sa.String(length=300), nullable=True),
    sa.Column('uan_file', sa.String(length=300), nullable=True),
    sa.Column('esic_file', sa.String(length=300), nullable=True),
    sa.Column('bank_details_file', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('man_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manpower_workers')
    # ### end Alembic commands ###
