"""add batching plant

Revision ID: 6509f4a3e0ad
Revises: dbb32a9d7745
Create Date: 2026-07-28 15:07:10.944297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6509f4a3e0ad'
down_revision = 'dbb32a9d7745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batching_plant_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('despatch_no', sa.String(length=50), nullable=False),
    sa.Column('bp_uuid', sa.String(length=36), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.Column('pw_order_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('material_type', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=100), nullable=True),
    sa.Column('unit_of_concrete', sa.String(length=50), nullable=True),
    sa.Column('volume_of_concrete', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('weight_of_concrete', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('production_unit_name', sa.String(length=100), nullable=True),
    sa.Column('operator_name', sa.String(length=100), nullable=True),
    sa.Column('production_completed', sa.String(length=100), nullable=True),
    sa.Column('batch_slip_no', sa.String(length=50), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('loading_finish_time', sa.String(length=50), nullable=True),
    sa.Column('pouring_start_time', sa.String(length=50), nullable=True),
    sa.Column('completion_time', sa.String(length=50), nullable=True),
    sa.Column('requisition_by', sa.String(length=100), nullable=True),
    sa.Column('requisition_date', sa.Date(), nullable=True),
    sa.Column('requisition_time', sa.String(length=50), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['pw_order_id'], ['pw_order_master.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('despatch_no')
    )
    with op.batch_alter_table('batching_plant_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batching_plant_master_bp_uuid'), ['bp_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batching_plant_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batching_plant_master_bp_uuid'))

    op.drop_table('batching_plant_master')
    # ### end Alembic commands ###
