"""Store location

Revision ID: 708a842532ab
Revises: 1a2441fda57f
Create Date: 2026-07-12 12:15:46.926402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708a842532ab'
down_revision = '1a2441fda57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projectlocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('location_type', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('Projectlocation_store_location_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('Projectlocation_use_location_key'), type_='unique')
        batch_op.create_unique_constraint('uq_project_location_name_type', ['project_code', 'location_name', 'location_type'])
        batch_op.drop_column('store_location')
        batch_op.drop_column('use_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projectlocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_location', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('store_location', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('uq_project_location_name_type', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('Projectlocation_use_location_key'), ['use_location'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('Projectlocation_store_location_key'), ['store_location'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('location_type')
        batch_op.drop_column('location_name')

    # ### end Alembic commands ###
