"""prefix suffix on og sale order header

Revision ID: 7cd6e480366d
Revises: d1f247c46802
Create Date: 2026-08-02 12:26:18.833861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd6e480366d'
down_revision = 'd1f247c46802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('og_sale_order_items', schema=None) as batch_op:
        batch_op.drop_column('suffix')
        batch_op.drop_column('prefix')

    with op.batch_alter_table('og_sale_order_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('suffix', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('og_sale_order_master', schema=None) as batch_op:
        batch_op.drop_column('suffix')
        batch_op.drop_column('prefix')

    with op.batch_alter_table('og_sale_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suffix', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
