"""make account_type nullable in journal lines

Revision ID: 801cdfbfbed4
Revises: 07f3183282f6
Create Date: 2026-09-01 18:51:04.934153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801cdfbfbed4'
down_revision = '07f3183282f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.alter_column('account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
