"""grn challan date

Revision ID: 82d83ca2c686
Revises: e61ed087ed88
Create Date: 2026-07-30 00:45:37.216810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d83ca2c686'
down_revision = 'e61ed087ed88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challan_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.drop_column('challan_date')

    # ### end Alembic commands ###
