"""fix

Revision ID: 8529f20243d8
Revises: e145c4653a5e
Create Date: 2026-08-02 17:23:55.054082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8529f20243d8'
down_revision = 'e145c4653a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_items', schema=None) as batch_op:
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
