""" pdf left and new billing fixed

Revision ID: 85e0157c7af7
Revises: ea9baed64f84
Create Date: 2026-07-22 10:04:48.239361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e0157c7af7'
down_revision = 'ea9baed64f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brg_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brg_no', sa.String(length=50), nullable=False),
    sa.Column('brg_date', sa.Date(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('brr_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('received_category', sa.String(length=100), nullable=True),
    sa.Column('item_category', sa.String(length=100), nullable=True),
    sa.Column('cost_head', sa.String(length=100), nullable=True),
    sa.Column('party_bill_no', sa.String(length=100), nullable=True),
    sa.Column('party_date', sa.Date(), nullable=True),
    sa.Column('site', sa.String(length=200), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('attached_doc', sa.Text(), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['brr_id'], ['brr_master.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order_master.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brg_no')
    )
    op.create_table('brs_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brs_no', sa.String(length=50), nullable=False),
    sa.Column('brs_date', sa.Date(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('brr_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('received_category', sa.String(length=100), nullable=True),
    sa.Column('item_category', sa.String(length=100), nullable=True),
    sa.Column('cost_head', sa.String(length=100), nullable=True),
    sa.Column('party_bill_no', sa.String(length=100), nullable=True),
    sa.Column('party_date', sa.Date(), nullable=True),
    sa.Column('site', sa.String(length=200), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('attached_doc', sa.Text(), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['brr_id'], ['brr_master.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['pw_order_master.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brs_no')
    )
    op.create_table('brg_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brg_id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('grn_item_id', sa.Integer(), nullable=False),
    sa.Column('billing_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brg_id'], ['brg_master.id'], ),
    sa.ForeignKeyConstraint(['grn_id'], ['grn_master.id'], ),
    sa.ForeignKeyConstraint(['grn_item_id'], ['grn_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brs_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brs_id', sa.Integer(), nullable=False),
    sa.Column('srn_id', sa.Integer(), nullable=False),
    sa.Column('srn_item_id', sa.Integer(), nullable=False),
    sa.Column('billing_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brs_id'], ['brs_master.id'], ),
    sa.ForeignKeyConstraint(['srn_id'], ['srn_master.id'], ),
    sa.ForeignKeyConstraint(['srn_item_id'], ['srn_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brr_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('pw_order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pw_order_master', ['pw_order_id'], ['id'])

    with op.batch_alter_table('gin_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gin_uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_gin_master_gin_uuid'), ['gin_uuid'], unique=True)

    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grn_uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_grn_master_grn_uuid'), ['grn_uuid'], unique=True)

    with op.batch_alter_table('srn_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('srn_uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_srn_master_srn_uuid'), ['srn_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('srn_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_srn_master_srn_uuid'))
        batch_op.drop_column('srn_uuid')

    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grn_master_grn_uuid'))
        batch_op.drop_column('grn_uuid')

    with op.batch_alter_table('gin_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gin_master_gin_uuid'))
        batch_op.drop_column('gin_uuid')

    with op.batch_alter_table('brr_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pw_order_id')
        batch_op.drop_column('order_type')

    op.drop_table('brs_items')
    op.drop_table('brg_items')
    op.drop_table('brs_master')
    op.drop_table('brg_master')
    # ### end Alembic commands ###
