"""pdf url in order master 

Revision ID: 88ed6184b763
Revises: cff23b28f345
Create Date: 2026-07-03 06:52:00.364496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ed6184b763'
down_revision = 'cff23b28f345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pdf_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pdf_generated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_master', schema=None) as batch_op:
        batch_op.drop_column('pdf_generated_at')
        batch_op.drop_column('pdf_token')
        batch_op.drop_column('pdf_url')

    # ### end Alembic commands ###
