"""fix

Revision ID: 8a322851e1a0
Revises: 8529f20243d8
Create Date: 2026-08-02 22:24:14.767933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a322851e1a0'
down_revision = '8529f20243d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claim_bill_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('billing_master_billing_no_key'), type_='unique')
        batch_op.create_foreign_key(None, 'billing_master', ['claim_bill_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('billing_master_billing_no_key'), ['billing_no'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('claim_bill_id')

    # ### end Alembic commands ###
