"""bbs register

Revision ID: 944d402c3c34
Revises: 6509f4a3e0ad
Create Date: 2026-07-28 23:38:35.172441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944d402c3c34'
down_revision = '6509f4a3e0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bbs_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bbs_no', sa.String(length=50), nullable=False),
    sa.Column('bbs_uuid', sa.String(length=36), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('revision', sa.String(length=50), nullable=True),
    sa.Column('bbs_title', sa.String(length=500), nullable=True),
    sa.Column('reference_order_no', sa.String(length=100), nullable=True),
    sa.Column('project_sub_location', sa.String(length=200), nullable=True),
    sa.Column('segment_layer', sa.String(length=200), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('received_time', sa.Time(), nullable=True),
    sa.Column('received_by', sa.String(length=200), nullable=True),
    sa.Column('delivered_by', sa.String(length=200), nullable=True),
    sa.Column('delivery_mode', sa.String(length=100), nullable=True),
    sa.Column('delivery_reference', sa.String(length=200), nullable=True),
    sa.Column('attachment', sa.Text(), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bbs_no')
    )
    with op.batch_alter_table('bbs_register', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bbs_register_bbs_uuid'), ['bbs_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bbs_register', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bbs_register_bbs_uuid'))

    op.drop_table('bbs_register')
    # ### end Alembic commands ###
