"""transfercode 

Revision ID: 953c3b5d3ba2
Revises: 
Create Date: 2026-06-21 15:09:39.555459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953c3b5d3ba2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_open_txn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('txn_description', sa.String(length=255), nullable=True),
    sa.Column('txn_started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machinery_log_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_book_no', sa.String(length=50), nullable=False),
    sa.Column('create_date', sa.Date(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('party_order_id', sa.Integer(), nullable=True),
    sa.Column('machinery_name', sa.String(length=200), nullable=True),
    sa.Column('machinery_reg_no', sa.String(length=100), nullable=True),
    sa.Column('fuel_consumption_unit', sa.String(length=50), nullable=True),
    sa.Column('fuel_consumption_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['party_order_id'], ['pw_order_master.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_book_no')
    )
    op.create_table('log_book_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_uid', sa.String(length=50), nullable=False),
    sa.Column('log_book_id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('running_date', sa.Date(), nullable=True),
    sa.Column('running_start_time', sa.Time(), nullable=True),
    sa.Column('running_finish_time', sa.Time(), nullable=True),
    sa.Column('project_sub_location', sa.String(length=200), nullable=True),
    sa.Column('segment_layer', sa.String(length=200), nullable=True),
    sa.Column('work_monitoring_by', sa.String(length=200), nullable=True),
    sa.Column('operator_name', sa.String(length=200), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['log_book_id'], ['machinery_log_book.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_uid')
    )
    with op.batch_alter_table('order_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_project_site', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'projects', ['transfer_project_site'], ['project_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('transfer_project_site')

    op.drop_table('log_book_entries')
    op.drop_table('machinery_log_book')
    op.drop_table('maintenance_open_txn')
    # ### end Alembic commands ###
