"""add pdf columns to grn_master

Revision ID: 981b9b070f76
Revises: 7e7f5e090cdd
Create Date: 2026-07-08 19:08:06.075335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981b9b070f76'
down_revision = '7e7f5e090cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pdf_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pdf_generated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.drop_column('pdf_generated_at')
        batch_op.drop_column('pdf_token')
        batch_op.drop_column('pdf_url')

    # ### end Alembic commands ###
