"""supplier project map

Revision ID: 9c70e479fafd
Revises: d4123d0bc72e
Create Date: 2026-07-16 20:17:22.393946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c70e479fafd'
down_revision = 'd4123d0bc72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_project_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'project_id', name='uq_supplier_project')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('nature_of_service',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='nature_of_service::json')
        batch_op.drop_constraint(batch_op.f('suppliers_project_code_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('suppliers_project_id_fkey'), type_='foreignkey')
        batch_op.drop_column('project_id')
        batch_op.drop_column('project_code')

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('nature_of_service',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='nature_of_service::json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('nature_of_service',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('suppliers_project_id_fkey'), 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('suppliers_project_code_fkey'), 'projects', ['project_code'], ['project_code'])
        batch_op.alter_column('nature_of_service',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    op.drop_table('supplier_project_map')
    # ### end Alembic commands ###
