"""ledger

Revision ID: 9cde0ca4ffc7
Revises: 85a8367c5fbf
Create Date: 2026-07-18 17:00:33.473533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cde0ca4ffc7'
down_revision = '85a8367c5fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['mobile_number'])
        batch_op.create_unique_constraint(None, ['registered_address'])
        batch_op.create_unique_constraint(None, ['corporate_address'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['pan'])
        batch_op.create_unique_constraint(None, ['corporate_address'])
        batch_op.create_unique_constraint(None, ['gstin'])
        batch_op.create_unique_constraint(None, ['registered_address'])
        batch_op.create_unique_constraint(None, ['primary_contact_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
