"""Order term

Revision ID: a175cfa54817
Revises: 
Create Date: 2026-07-18 17:29:48.635147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a175cfa54817'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_terms_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_term_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'terms', ['source_term_id'], ['term_id'])

    with op.batch_alter_table('pw_order_terms_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_term_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'terms', ['source_term_id'], ['term_id'])

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['corporate_address'])
        batch_op.create_unique_constraint(None, ['mobile_number'])
        batch_op.create_unique_constraint(None, ['registered_address'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['gstin'])
        batch_op.create_unique_constraint(None, ['primary_contact_number'])
        batch_op.create_unique_constraint(None, ['pan'])
        batch_op.create_unique_constraint(None, ['corporate_address'])
        batch_op.create_unique_constraint(None, ['registered_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('pw_order_terms_conditions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_term_id')

    with op.batch_alter_table('order_terms_conditions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_term_id')

    # ### end Alembic commands ###
