""" pdf left and new billing fixed

Revision ID: ab20c12b9215
Revises: 85e0157c7af7
Create Date: 2026-07-23 14:44:20.209300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab20c12b9215'
down_revision = '85e0157c7af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brb_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brb_no', sa.String(length=50), nullable=False),
    sa.Column('brb_date', sa.Date(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('brr_id', sa.Integer(), nullable=False),
    sa.Column('billing_type', sa.String(length=10), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('item_category', sa.String(length=255), nullable=True),
    sa.Column('cost_head', sa.String(length=100), nullable=True),
    sa.Column('party_bill_no', sa.String(length=100), nullable=True),
    sa.Column('party_date', sa.Date(), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('attached_doc', sa.Text(), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['brr_id'], ['brr_master.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brb_no')
    )
    op.create_table('brb_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brb_id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=True),
    sa.Column('grn_item_id', sa.Integer(), nullable=True),
    sa.Column('srn_id', sa.Integer(), nullable=True),
    sa.Column('srn_item_id', sa.Integer(), nullable=True),
    sa.Column('billing_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brb_id'], ['brb_master.id'], ),
    sa.ForeignKeyConstraint(['grn_id'], ['grn_master.id'], ),
    sa.ForeignKeyConstraint(['grn_item_id'], ['grn_items.id'], ),
    sa.ForeignKeyConstraint(['srn_id'], ['srn_master.id'], ),
    sa.ForeignKeyConstraint(['srn_item_id'], ['srn_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('brs_items')
    op.drop_table('brs_master')
    op.drop_table('brg_items')
    op.drop_table('brg_master')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brs_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brs_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('srn_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('srn_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('billing_qty', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('rate', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brs_id'], ['brs_master.id'], name=op.f('brs_items_brs_id_fkey')),
    sa.ForeignKeyConstraint(['srn_id'], ['srn_master.id'], name=op.f('brs_items_srn_id_fkey')),
    sa.ForeignKeyConstraint(['srn_item_id'], ['srn_items.id'], name=op.f('brs_items_srn_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('brs_items_pkey'))
    )
    op.create_table('brg_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brg_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('brg_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('brr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('received_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('item_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cost_head', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('party_bill_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('party_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('billing_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shipping_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('basic_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('attached_doc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('workflow_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('current_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('submitted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rejected_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('final_approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rejected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('correction_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('brg_master_approved_by_fkey')),
    sa.ForeignKeyConstraint(['brr_id'], ['brr_master.id'], name=op.f('brg_master_brr_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('brg_master_created_by_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['order_master.id'], name=op.f('brg_master_order_id_fkey')),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], name=op.f('brg_master_project_code_fkey')),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], name=op.f('brg_master_rejected_by_fkey')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('brg_master_submitted_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('brg_master_updated_by_fkey')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('brg_master_vendor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('brg_master_pkey')),
    sa.UniqueConstraint('brg_no', name=op.f('brg_master_brg_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('brg_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grn_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grn_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('billing_qty', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('rate', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brg_id'], ['brg_master.id'], name=op.f('brg_items_brg_id_fkey')),
    sa.ForeignKeyConstraint(['grn_id'], ['grn_master.id'], name=op.f('brg_items_grn_id_fkey')),
    sa.ForeignKeyConstraint(['grn_item_id'], ['grn_items.id'], name=op.f('brg_items_grn_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('brg_items_pkey'))
    )
    op.create_table('brs_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brs_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('brs_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('brr_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('received_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('item_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cost_head', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('party_bill_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('party_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('billing_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shipping_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('basic_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('attached_doc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('workflow_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('current_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('submitted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rejected_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('final_approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rejected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('correction_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('brs_master_approved_by_fkey')),
    sa.ForeignKeyConstraint(['brr_id'], ['brr_master.id'], name=op.f('brs_master_brr_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('brs_master_created_by_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['pw_order_master.id'], name=op.f('brs_master_order_id_fkey')),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], name=op.f('brs_master_project_code_fkey')),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], name=op.f('brs_master_rejected_by_fkey')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('brs_master_submitted_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('brs_master_updated_by_fkey')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('brs_master_vendor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('brs_master_pkey')),
    sa.UniqueConstraint('brs_no', name=op.f('brs_master_brs_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('brb_items')
    op.drop_table('brb_master')
    # ### end Alembic commands ###
