"""challan 

Revision ID: b57a8947d10b
Revises: 953c3b5d3ba2
Create Date: 2026-06-22 14:08:12.564366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57a8947d10b'
down_revision = '953c3b5d3ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dc_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dc_no', sa.String(length=50), nullable=False),
    sa.Column('challan_date', sa.Date(), nullable=False),
    sa.Column('order_type', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_vendor_id', sa.Integer(), nullable=True),
    sa.Column('from_project_code', sa.String(length=50), nullable=True),
    sa.Column('shipping_from_address', sa.Text(), nullable=True),
    sa.Column('to_project_code', sa.String(length=50), nullable=False),
    sa.Column('shipping_to_address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('purpose_for_delivery', sa.String(length=200), nullable=True),
    sa.Column('delivery_mode', sa.String(length=100), nullable=True),
    sa.Column('vehicle_number', sa.String(length=100), nullable=True),
    sa.Column('driver_name', sa.String(length=150), nullable=True),
    sa.Column('driver_contact_number', sa.String(length=20), nullable=True),
    sa.Column('eway_bill_number', sa.String(length=100), nullable=True),
    sa.Column('eway_bill_date', sa.Date(), nullable=True),
    sa.Column('eway_bill_expiry_date', sa.Date(), nullable=True),
    sa.Column('attached_doc', sa.Text(), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['from_vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order_master.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dc_no')
    )
    op.create_table('dc_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=True),
    sa.Column('issue_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock_location', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['dc_master.id'], ),
    sa.ForeignKeyConstraint(['item_code'], ['items.item_code'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dc_items')
    op.drop_table('dc_master')
    # ### end Alembic commands ###
