"""budget

Revision ID: b5bab715a1ec
Revises: 801cdfbfbed4
Create Date: 2026-09-04 20:39:10.342351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bab715a1ec'
down_revision = '801cdfbfbed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petty_cash_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_uuid', sa.String(length=36), nullable=True),
    sa.Column('budget_no', sa.String(length=30), nullable=False),
    sa.Column('budget_date', sa.Date(), nullable=False),
    sa.Column('budget_frequency', sa.String(length=20), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('total_budget_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('petty_cash_budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_petty_cash_budget_budget_uuid'), ['budget_uuid'], unique=True)

    op.create_table('petty_cash_budget_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('cc_code', sa.String(length=20), nullable=True),
    sa.Column('cc_name', sa.String(length=100), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['petty_cash_budget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('petty_cash_budget_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('detail_row_id', sa.Integer(), nullable=False),
    sa.Column('revised_by', sa.Integer(), nullable=False),
    sa.Column('revised_at', sa.DateTime(), nullable=True),
    sa.Column('old_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('new_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['petty_cash_budget.id'], ),
    sa.ForeignKeyConstraint(['detail_row_id'], ['petty_cash_budget_detail.id'], ),
    sa.ForeignKeyConstraint(['revised_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('petty_cash_budget_revision')
    op.drop_table('petty_cash_budget_detail')
    with op.batch_alter_table('petty_cash_budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_petty_cash_budget_budget_uuid'))

    op.drop_table('petty_cash_budget')
    # ### end Alembic commands ###
