"""vendor

Revision ID: be03ab8f3d7f
Revises: 561caaded4f0
Create Date: 2026-07-16 19:16:25.298331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be03ab8f3d7f'
down_revision = '561caaded4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('project_code', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_code'], ['project_code'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('category_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('category_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_code')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
