"""restructure sale receipt parent-child BRR pattern

Revision ID: c3fb74831f79
Revises: 34ae9d371baa
Create Date: 2026-08-08 17:53:47.465000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3fb74831f79'
down_revision = '34ae9d371baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_receipt_billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('srb_no', sa.String(length=50), nullable=False),
    sa.Column('srb_uuid', sa.String(length=36), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('og_sale_order_no', sa.String(length=50), nullable=True),
    sa.Column('og_sale_order_id', sa.Integer(), nullable=True),
    sa.Column('sale_order_date', sa.Date(), nullable=True),
    sa.Column('certified_bill_id', sa.Integer(), nullable=True),
    sa.Column('certified_bill_no', sa.String(length=50), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('invoice_no', sa.String(length=200), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('bill_to_address', sa.Text(), nullable=True),
    sa.Column('ship_to_address', sa.Text(), nullable=True),
    sa.Column('bill_abstract_no', sa.String(length=200), nullable=True),
    sa.Column('bill_abstract_date', sa.Date(), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('round_off', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_invoice_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['certified_bill_id'], ['billing_master.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['og_sale_order_id'], ['og_sale_order_master.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['sale_receipt_master.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_receipt_billing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_receipt_billing_srb_uuid'), ['srb_uuid'], unique=True)

    with op.batch_alter_table('sale_receipt_gst', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sale_receipt_gst_receipt_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sale_receipt_billing', ['receipt_id'], ['id'])

    with op.batch_alter_table('sale_receipt_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sale_receipt_items_receipt_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sale_receipt_billing', ['receipt_id'], ['id'])

    with op.batch_alter_table('sale_receipt_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.drop_constraint(batch_op.f('sale_receipt_master_certified_bill_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('sale_receipt_master_rejected_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('sale_receipt_master_og_sale_order_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('sale_receipt_master_approved_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('sale_receipt_master_submitted_by_fkey'), type_='foreignkey')
        batch_op.drop_column('og_sale_order_id')
        batch_op.drop_column('round_off')
        batch_op.drop_column('invoice_no')
        batch_op.drop_column('workflow_status')
        batch_op.drop_column('invoice_date')
        batch_op.drop_column('basic_amount')
        batch_op.drop_column('bill_abstract_no')
        batch_op.drop_column('final_approved_at')
        batch_op.drop_column('og_sale_order_no')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('bill_to_address')
        batch_op.drop_column('current_level')
        batch_op.drop_column('certified_bill_id')
        batch_op.drop_column('discount')
        batch_op.drop_column('sale_order_date')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('total_invoice_amount')
        batch_op.drop_column('rejected_by')
        batch_op.drop_column('locked')
        batch_op.drop_column('bill_abstract_date')
        batch_op.drop_column('gst_amount')
        batch_op.drop_column('correction_sent_at')
        batch_op.drop_column('submitted_by')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('ship_to_address')
        batch_op.drop_column('status')
        batch_op.drop_column('certified_bill_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_receipt_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certified_bill_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ship_to_address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('submitted_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('correction_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gst_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bill_abstract_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rejected_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_invoice_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sale_order_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('discount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('certified_bill_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_level', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bill_to_address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rejected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('og_sale_order_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('final_approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bill_abstract_no', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('basic_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('workflow_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_no', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('round_off', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('og_sale_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('sale_receipt_master_submitted_by_fkey'), 'users', ['submitted_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('sale_receipt_master_approved_by_fkey'), 'users', ['approved_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('sale_receipt_master_og_sale_order_id_fkey'), 'og_sale_order_master', ['og_sale_order_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('sale_receipt_master_rejected_by_fkey'), 'users', ['rejected_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('sale_receipt_master_certified_bill_id_fkey'), 'billing_master', ['certified_bill_id'], ['id'])
        batch_op.drop_column('total_amount')

    with op.batch_alter_table('sale_receipt_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sale_receipt_items_receipt_id_fkey'), 'sale_receipt_master', ['receipt_id'], ['id'])

    with op.batch_alter_table('sale_receipt_gst', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sale_receipt_gst_receipt_id_fkey'), 'sale_receipt_master', ['receipt_id'], ['id'])

    with op.batch_alter_table('sale_receipt_billing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_receipt_billing_srb_uuid'))

    op.drop_table('sale_receipt_billing')
    # ### end Alembic commands ###
