"""add budget tables

Revision ID: c66d96f02c68
Revises: cad07b84786c
Create Date: 2026-09-08 18:41:56.394956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66d96f02c68'
down_revision = 'cad07b84786c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_no', sa.String(length=50), nullable=False),
    sa.Column('budget_uuid', sa.String(length=36), nullable=True),
    sa.Column('budget_date', sa.Date(), nullable=False),
    sa.Column('sale_order_id', sa.Integer(), nullable=False),
    sa.Column('sale_order_no', sa.String(length=50), nullable=True),
    sa.Column('sale_order_title', sa.String(length=200), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('total_initial_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_cc_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_order_id'], ['og_sale_order_master.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_no')
    )
    with op.batch_alter_table('budget_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_master_budget_uuid'), ['budget_uuid'], unique=True)

    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('og_sale_order_item_id', sa.Integer(), nullable=True),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=2000), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('order_qty', sa.Numeric(precision=17, scale=4), nullable=True),
    sa.Column('rate', sa.Numeric(precision=17, scale=4), nullable=True),
    sa.Column('initial_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_cc_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budget_master.id'], ),
    sa.ForeignKeyConstraint(['og_sale_order_item_id'], ['og_sale_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_item_cc_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_item_id', sa.Integer(), nullable=False),
    sa.Column('cc_code_id', sa.Integer(), nullable=False),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=200), nullable=True),
    sa.Column('cc_value', sa.Numeric(precision=17, scale=4), nullable=True),
    sa.Column('cc_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['budget_item_id'], ['budget_items.id'], ),
    sa.ForeignKeyConstraint(['cc_code_id'], ['cc_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_item_cc_codes')
    op.drop_table('budget_items')
    with op.batch_alter_table('budget_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_master_budget_uuid'))

    op.drop_table('budget_master')
    # ### end Alembic commands ###
