"""Gross fix

Revision ID: ca81a0bf86f4
Revises: 3c99cab2349d
Create Date: 2026-07-18 18:37:48.570612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca81a0bf86f4'
down_revision = '3c99cab2349d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_terms_conditions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_terms_conditions_term_id_fkey'), type_='foreignkey')
        batch_op.drop_column('term_id')

    with op.batch_alter_table('pw_order_terms_conditions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pw_order_terms_conditions_term_id_fkey'), type_='foreignkey')
        batch_op.drop_column('term_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pw_order_terms_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('pw_order_terms_conditions_term_id_fkey'), 'terms', ['term_id'], ['term_id'])

    with op.batch_alter_table('order_terms_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('order_terms_conditions_term_id_fkey'), 'terms', ['term_id'], ['term_id'])

    # ### end Alembic commands ###
