"""docket voucher bank cash link

Revision ID: cad07b84786c
Revises: 1bcc564b404f
Create Date: 2026-09-06 17:30:35.738323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad07b84786c'
down_revision = '1bcc564b404f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petty_cash_docket_voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_cash_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bank_cash', ['bank_cash_id'], ['id'])
        batch_op.drop_column('fund_source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petty_cash_docket_voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fund_source', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bank_cash_id')

    # ### end Alembic commands ###
