"""bank added 

Revision ID: cff23b28f345
Revises: 45dbfed2db31
Create Date: 2026-06-24 17:08:17.498741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff23b28f345'
down_revision = '45dbfed2db31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_cash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('bank_code', sa.String(length=100), nullable=False),
    sa.Column('bank_holder_name', sa.String(length=200), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('branch_name', sa.String(length=200), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('micr_code', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('branch_manager_name', sa.String(length=200), nullable=True),
    sa.Column('branch_manager_contact', sa.String(length=20), nullable=True),
    sa.Column('branch_manager_email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_cash')
    # ### end Alembic commands ###
