"""og sale order item new fields

Revision ID: d1f247c46802
Revises: 53231f5d3f89
Create Date: 2026-08-02 12:07:49.831880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f247c46802'
down_revision = '53231f5d3f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('og_sale_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('item_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prefix', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('suffix', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('og_sale_order_items', schema=None) as batch_op:
        batch_op.drop_column('suffix')
        batch_op.drop_column('prefix')
        batch_op.drop_column('item_description')
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
