"""vendor fix

Revision ID: d4123d0bc72e
Revises: be03ab8f3d7f
Create Date: 2026-07-16 19:21:10.739038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4123d0bc72e'
down_revision = 'be03ab8f3d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('nature_of_service',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('nature_of_service',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('nature_of_service',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('nature_of_service',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
