"""add pm_master service_history service_schedule tables

Revision ID: dbb32a9d7745
Revises: 281c1dbe36ef
Create Date: 2026-07-26 15:35:24.688627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb32a9d7745'
down_revision = '281c1dbe36ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pm_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pm_uid', sa.String(length=20), nullable=False),
    sa.Column('machine_name', sa.String(length=200), nullable=True),
    sa.Column('machinery_type', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('registration_file', sa.String(length=300), nullable=True),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_date', sa.Date(), nullable=True),
    sa.Column('insurance_file', sa.String(length=300), nullable=True),
    sa.Column('puc_cert_number', sa.String(length=100), nullable=True),
    sa.Column('puc_date', sa.Date(), nullable=True),
    sa.Column('puc_file', sa.String(length=300), nullable=True),
    sa.Column('road_tax_number', sa.String(length=100), nullable=True),
    sa.Column('road_tax_date', sa.Date(), nullable=True),
    sa.Column('road_tax_file', sa.String(length=300), nullable=True),
    sa.Column('fuel_consumption_unit', sa.String(length=100), nullable=True),
    sa.Column('purchased_bill_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchased_bill_date', sa.Date(), nullable=True),
    sa.Column('purchased_bill_file', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pm_uid')
    )
    op.create_table('pm_service_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pm_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('bill_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('party_bill_no', sa.String(length=100), nullable=True),
    sa.Column('party_bill_file', sa.String(length=300), nullable=True),
    sa.Column('service_location', sa.String(length=200), nullable=True),
    sa.Column('job_monitoring_by', sa.String(length=200), nullable=True),
    sa.Column('operator_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pm_id'], ['pm_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pm_service_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pm_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('reading_under', sa.String(length=100), nullable=True),
    sa.Column('expected_expenses', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('responsible_person', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pm_id'], ['pm_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pm_service_schedule')
    op.drop_table('pm_service_history')
    op.drop_table('pm_master')
    # ### end Alembic commands ###
