"""contra entry

Revision ID: e031731d7653
Revises: 28ccf41b2523
Create Date: 2026-08-04 15:37:19.780759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e031731d7653'
down_revision = '28ccf41b2523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contra_entry_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_no', sa.String(length=50), nullable=False),
    sa.Column('contra_uuid', sa.String(length=36), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contra_entry_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contra_entry_master_contra_uuid'), ['contra_uuid'], unique=True)

    op.create_table('contra_entry_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contra_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('dr_cr', sa.String(length=3), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['bank_cash.id'], ),
    sa.ForeignKeyConstraint(['contra_id'], ['contra_entry_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contra_entry_lines')
    with op.batch_alter_table('contra_entry_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contra_entry_master_contra_uuid'))

    op.drop_table('contra_entry_master')
    # ### end Alembic commands ###
