"""bilinf and item display code add

Revision ID: e145c4653a5e
Revises: 7cd6e480366d
Create Date: 2026-08-02 15:03:56.132014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e145c4653a5e'
down_revision = '7cd6e480366d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_no', sa.String(length=50), nullable=False),
    sa.Column('billing_uuid', sa.String(length=36), nullable=True),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('og_sale_order_no', sa.String(length=50), nullable=True),
    sa.Column('og_sale_order_id', sa.Integer(), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('job_location', sa.String(length=500), nullable=True),
    sa.Column('attachment', sa.Text(), nullable=True),
    sa.Column('pre_certified_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('this_bill_claim', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_claim', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['og_sale_order_id'], ['og_sale_order_master.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_no')
    )
    with op.batch_alter_table('billing_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_master_billing_uuid'), ['billing_uuid'], unique=True)

    op.create_table('billing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('og_sale_order_item_id', sa.Integer(), nullable=True),
    sa.Column('item_code', sa.String(length=50), nullable=True),
    sa.Column('item_name_desc', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('claim_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_id'], ['billing_master.id'], ),
    sa.ForeignKeyConstraint(['og_sale_order_item_id'], ['og_sale_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certified_bill_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certified_bill_master_certified_bill_uuid'))

    op.drop_table('certified_bill_master')
    with op.batch_alter_table('sale_order_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_order_master_sale_order_uuid'))

    op.drop_table('sale_order_master')
    op.drop_table('certified_bill_items')
    op.drop_table('sale_order_items')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_display_code', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('item_display_code')

    op.create_table('sale_order_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sl_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('item_name_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('claim_qty', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('rate', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('og_sale_order_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['og_sale_order_item_id'], ['og_sale_order_items.id'], name=op.f('sale_order_items_og_sale_order_item_id_fkey')),
    sa.ForeignKeyConstraint(['sale_order_id'], ['sale_order_master.id'], name=op.f('sale_order_items_sale_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sale_order_items_pkey'))
    )
    op.create_table('certified_bill_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('certified_bill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sl_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('item_name_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('claim_qty', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('rate', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['certified_bill_id'], ['certified_bill_master.id'], name=op.f('certified_bill_items_certified_bill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('certified_bill_items_pkey'))
    )
    op.create_table('sale_order_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_order_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sale_order_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('sale_order_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('job_location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('pre_certified_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('this_bill_claim', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_claim', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('attachment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('workflow_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('current_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('submitted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('final_approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rejected_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rejected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('correction_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('og_sale_order_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('og_sale_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('sale_order_master_approved_by_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('sale_order_master_created_by_fkey')),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], name=op.f('sale_order_master_project_code_fkey')),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], name=op.f('sale_order_master_rejected_by_fkey')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('sale_order_master_submitted_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('sale_order_master_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sale_order_master_pkey')),
    sa.UniqueConstraint('sale_order_no', name=op.f('sale_order_master_sale_order_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('sale_order_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_order_master_sale_order_uuid'), ['sale_order_uuid'], unique=True)

    op.create_table('certified_bill_master',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('certified_bill_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('certified_bill_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('certified_bill_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('order_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('project_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('job_location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('pre_certified_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('this_bill_claim', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('gst_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_claim', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('attachment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('workflow_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('current_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('submitted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('final_approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rejected_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rejected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('correction_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('certified_bill_master_approved_by_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('certified_bill_master_created_by_fkey')),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], name=op.f('certified_bill_master_project_code_fkey')),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], name=op.f('certified_bill_master_rejected_by_fkey')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('certified_bill_master_submitted_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('certified_bill_master_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('certified_bill_master_pkey')),
    sa.UniqueConstraint('certified_bill_no', name=op.f('certified_bill_master_certified_bill_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('certified_bill_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certified_bill_master_certified_bill_uuid'), ['certified_bill_uuid'], unique=True)

    op.drop_table('billing_items')
    with op.batch_alter_table('billing_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_master_billing_uuid'))

    op.drop_table('billing_master')
    # ### end Alembic commands ###
