"""companyBillingAddress 

Revision ID: e1b6adf9186d
Revises: b57a8947d10b
Create Date: 2026-06-23 11:55:43.757347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b6adf9186d'
down_revision = 'b57a8947d10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_billing_address', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('company_billing_address')

    # ### end Alembic commands ###
