"""hindrance register

Revision ID: e61ed087ed88
Revises: 944d402c3c34
Create Date: 2026-07-29 01:10:55.189398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61ed087ed88'
down_revision = '944d402c3c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hindrance_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hindrance_no', sa.String(length=50), nullable=False),
    sa.Column('hindrance_uuid', sa.String(length=36), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('hindrance_date', sa.Date(), nullable=True),
    sa.Column('title_of_hindrance', sa.String(length=500), nullable=True),
    sa.Column('cause_of_hindrance', sa.Text(), nullable=True),
    sa.Column('manpower_details', sa.Text(), nullable=True),
    sa.Column('manpower_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('plant_machinery_details', sa.Text(), nullable=True),
    sa.Column('plant_machinery_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('materials_details', sa.Text(), nullable=True),
    sa.Column('materials_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_effected_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('attachment', sa.Text(), nullable=True),
    sa.Column('intimation_to', sa.String(length=200), nullable=True),
    sa.Column('intimation_via', sa.String(length=100), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hindrance_no')
    )
    with op.batch_alter_table('hindrance_register', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hindrance_register_hindrance_uuid'), ['hindrance_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hindrance_register', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hindrance_register_hindrance_uuid'))

    op.drop_table('hindrance_register')
    # ### end Alembic commands ###
