""" order uuid add

Revision ID: ea9baed64f84
Revises: 0f89bfca854d
Create Date: 2026-07-21 12:41:58.840340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9baed64f84'
down_revision = '0f89bfca854d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_master_order_uuid'), ['order_uuid'], unique=True)

    with op.batch_alter_table('pw_order_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_pw_order_master_order_uuid'), ['order_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pw_order_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pw_order_master_order_uuid'))
        batch_op.drop_column('order_uuid')

    with op.batch_alter_table('order_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_master_order_uuid'))
        batch_op.drop_column('order_uuid')

    # ### end Alembic commands ###
