"""fix

Revision ID: efde87db42ab
Revises: e031731d7653
Create Date: 2026-08-04 18:25:28.721659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efde87db42ab'
down_revision = 'e031731d7653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('og_sale_order_boq_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('og_sale_order_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.String(length=2000), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('item_name_desc', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('order_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['og_sale_order_id'], ['og_sale_order_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_boq_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=True),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('item_name_desc', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('claim_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_id'], ['billing_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('billing_items_og_sale_order_item_id_fkey'), type_='foreignkey')
        batch_op.drop_column('og_sale_order_item_id')

    with op.batch_alter_table('og_sale_order_items', schema=None) as batch_op:
        batch_op.alter_column('item_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('og_sale_order_items_item_code_fkey'), type_='foreignkey')

    with op.batch_alter_table('og_sale_order_master', schema=None) as batch_op:
        batch_op.drop_column('suffix')
        batch_op.drop_column('prefix')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('og_sale_order_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('suffix', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('og_sale_order_items', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('og_sale_order_items_item_code_fkey'), 'items', ['item_code'], ['item_code'])
        batch_op.alter_column('item_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('billing_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('og_sale_order_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('billing_items_og_sale_order_item_id_fkey'), 'og_sale_order_items', ['og_sale_order_item_id'], ['id'])

    op.drop_table('billing_boq_items')
    op.drop_table('og_sale_order_boq_items')
    # ### end Alembic commands ###
