"""accounts

Revision ID: f14ba9af90f4
Revises: 8a322851e1a0
Create Date: 2026-08-03 17:11:09.954869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14ba9af90f4'
down_revision = '8a322851e1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_bill_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_bill_no', sa.String(length=50), nullable=False),
    sa.Column('sale_bill_uuid', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('reference_no', sa.String(length=200), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.Column('sale_order_no', sa.String(length=50), nullable=True),
    sa.Column('sale_order_id', sa.Integer(), nullable=True),
    sa.Column('certified_bill_id', sa.Integer(), nullable=True),
    sa.Column('certified_bill_no', sa.String(length=50), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('bill_to_address', sa.Text(), nullable=True),
    sa.Column('ship_to_address', sa.Text(), nullable=True),
    sa.Column('bill_abstract_no', sa.String(length=200), nullable=True),
    sa.Column('bill_abstract_date', sa.Date(), nullable=True),
    sa.Column('bank_ac', sa.String(length=200), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('declaration', sa.Text(), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('round_off', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_invoice_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['certified_bill_id'], ['billing_master.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_order_id'], ['og_sale_order_master.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_bill_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_bill_master_sale_bill_uuid'), ['sale_bill_uuid'], unique=True)

    op.create_table('sale_bill_gst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_bill_id', sa.Integer(), nullable=False),
    sa.Column('gst_type', sa.String(length=10), nullable=False),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_bill_id'], ['sale_bill_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_bill_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_bill_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hsn_sac', sa.String(length=50), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_bill_id'], ['sale_bill_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_bill_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_bill_no', sa.String(length=50), nullable=False),
    sa.Column('purchase_bill_uuid', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('processing_date', sa.Date(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('pw_order_id', sa.Integer(), nullable=True),
    sa.Column('brr_id', sa.Integer(), nullable=True),
    sa.Column('brr_no', sa.String(length=50), nullable=True),
    sa.Column('brr_date', sa.Date(), nullable=True),
    sa.Column('vendor_bill_no', sa.String(length=100), nullable=True),
    sa.Column('vendor_bill_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('round_off', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_invoice_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('correction_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['brr_id'], ['brr_master.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order_master.id'], ),
    sa.ForeignKeyConstraint(['project_code'], ['projects.project_code'], ),
    sa.ForeignKeyConstraint(['pw_order_id'], ['pw_order_master.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_bill_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_bill_master_purchase_bill_uuid'), ['purchase_bill_uuid'], unique=True)

    op.create_table('purchase_bill_gst',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_bill_id', sa.Integer(), nullable=False),
    sa.Column('gst_type', sa.String(length=10), nullable=False),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_bill_id'], ['purchase_bill_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_bill_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_bill_id', sa.Integer(), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('cc_code', sa.String(length=50), nullable=True),
    sa.Column('cc_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hsn_sac', sa.String(length=50), nullable=True),
    sa.Column('basic_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_bill_id'], ['purchase_bill_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_bill_items')
    op.drop_table('purchase_bill_gst')
    with op.batch_alter_table('purchase_bill_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_bill_master_purchase_bill_uuid'))

    op.drop_table('purchase_bill_master')
    op.drop_table('sale_bill_items')
    op.drop_table('sale_bill_gst')
    with op.batch_alter_table('sale_bill_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_bill_master_sale_bill_uuid'))

    op.drop_table('sale_bill_master')
    # ### end Alembic commands ###
