"""term

Revision ID: fc2f4f554911
Revises: 17f01df781b0
Create Date: 2026-07-18 14:12:31.993955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2f4f554911'
down_revision = '17f01df781b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_terms_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_groups', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('order_terms_conditions_term_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'terms', ['term_id'], ['term_id'])
        batch_op.drop_column('custom_description')

    with op.batch_alter_table('pw_order_terms_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_groups', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('pw_order_terms_conditions_term_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'terms', ['term_id'], ['term_id'])
        batch_op.drop_column('custom_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pw_order_terms_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pw_order_terms_conditions_term_id_fkey'), 'term_conditions', ['term_id'], ['id'])
        batch_op.drop_column('custom_groups')

    with op.batch_alter_table('order_terms_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_terms_conditions_term_id_fkey'), 'term_conditions', ['term_id'], ['id'])
        batch_op.drop_column('custom_groups')

    # ### end Alembic commands ###
