"""add pdf columns to grn_master

Revision ID: ff87f6de6fd8
Revises: 08953e7e5677
Create Date: 2026-07-08 09:57:32.427655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff87f6de6fd8'
down_revision = '08953e7e5677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pdf_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pdf_generated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.drop_column('pdf_generated_at')
        batch_op.drop_column('pdf_token')
        batch_op.drop_column('pdf_url')

    # ### end Alembic commands ###
