name: Deploy to Hetzner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 167.233.108.123
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/prax-erp
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart prax-erp
