name: Deploy Backend

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export FLASK_APP=run.py
            cd /srv/backend
            git pull origin master
            source venv/bin/activate
            pip install -r requirements.txt
            flask db upgrade
            sudo systemctl restart backend.service